pilifana:
  # Update intrerval in seconds
  interval: 10
  metric: pilifana
logging:
  format: "%(asctime)s [%(levelname)s] |==> %(message)s"
  level: DEBUG
services:
  pilight:
    host: http://127.0.0.1:5001
    authentication: basic
    # Uncomment this line to enable authentication with Basic Auth
    # authentication: basic
    # username: user
    # password: secret
  kairosdb:
    host: http://127.0.0.1:8080
    authentication: none
    # Uncomment this line to enable authentication with Basic Auth
    # authentication: basic
    # username: user
    # password: secret
